export interface IUsuario {
    id?:            string | number,
    nombre:         string,
    apellido:       string,
    login:          string,
    password:       string,
    perfil_id:      string | number,
    email:          string,
    tema:           string,
    app_ajax:       number,
    datagrid:       number,
    imagen:         string,
    pool:           string,
    usuario_at:     string,
    usuario_in:     string,
    caja_id:        string | number,
    vendedor_id:    string | number,
}