export interface IUsuario {
    id?:                string | number,
    nombre:             string,
    apellido:           string,
    fecha_nac:          string,
    recovery:           string,
    recoverydate :      string,
    login:              string,
    password:           string,
    perfil_id:          string | number,
    email:              string,
    tema:               string,
    app_ajax:           number,
    datagrid:           number,
    adm_empresa_id:     number | string,
    imagen:             string,
    pool:               string,
    usuario_at:         string,
    usuario_in:         string,
    adm_caja_id:        string | number,
    adm_vendedor_id:    string | number,
    telefono:           string,
    bloqueado:          number,
}