export interface IEmpresa {
    id?:                    string | number,
    rif:                    string,
    razon_social:           string,
    nombre_comercial:       string,
    fecha_registro:         string,
    direccion:              string,
    telefono1:              string,
    telefono2:              string,
    telefono3:              string,
    pag_web:                string,
    correo_electronico:     string,
    correo_electronico2:    string,
    twitter:                string,
    facebook:               string,
    instagram:              string,
 //   logo:                   string,
    imagen:string,
    firma_digital:          string,
    tipo_imagen:            string,
    licencia_licores:       boolean | number,
    nota:                   string,
    marca_agua:             string,
    tipo_calculo:           number,
    contribuyente_especial: boolean | number,
    nota2:                  string,
    color_presupuesto:      string,
    img_barcode:            string,
    modelo:                 number,
    estado_id:              string | number,
    municipio_id:           string | number,
}