## New extended consult
GET http://localhost:81/api/conceptos/?fields=id,nombre,codigo&grupos_id=2&grupos_id=3
x-access-control : {"user":"admin","password":"123456"}


## Total prueba
GET http://localhost:81/api/conceptos/mostsold/?after-fecha_at=2019-07-18&before-fecha_at=2019-08-07
x-access-control : {"user":"admin","password":"123456"}

POST http://localhost:81/api/usuario/login
x-access-control : {"user":"admin","password":"123456"}
content-type: application/json

{
    "data":{
        "usuario" : "ducen29@gmail.com",
        "password": "2423503"
    }
}

POST http://localhost:81/api/movimiento_deposito/1
x-access-control : {"user":"admin","password":"123456"}
content-type: application/json

{
    "data":{
        "existencia" : 100
    }
}

GET  http://localhost:81/api/movimiento_deposito/
x-access-control : {"user":"admin","password":"123456"}
