## New extended consult
GET http://localhost:81/api/factura/1
x-access-control : {"user":"admin","password":"123456"}


## Total prueba
GET http://localhost:81/api/conceptos/mostsold/?after-fecha_at=2019-07-18&before-fecha_at=2019-08-07
x-access-control : {"user":"admin","password":"123456"}

POST http://localhost:81/api/usuario/login
x-access-control : {"user":"admin","password":"123456"}
content-type: application/json

{
    "data":{
        "usuario" : "ducen29@gmail.com",
        "password": "2423503"
    }
}

POST http://localhost:81/api/grupos/
x-access-control : {"user":"admin","password":"123456"}
content-type: application/json

{
    "data":{
        "nombre" : "GRUPO DE PRUEBA",
    }
}

GET   http://localhost:81/api/grupos/1/conceptos/?fields=id,nombre,empresa_id,grupos_id
x-access-control : {"user":"admin","password":"12456"}
content-type: application/json
