export interface IMovimientoBanco {
    id?: number | string,
    adm_banco_id: number | string,
    adm_tipo_movimiento_id: number | string,
    adm_caja_id?: number | string,
    fecha_at?: string,
    adm_tipo_pago_id: number | string,
    referencia?: string,
    credito?: number,
    credito_dolar?: number,
    debito?: number,
    descripcion?: string,
    beneficiario?: number,
    adm_entidad_id?: number | string,
    origen: string,
    documento: number | string,
    efectivo?: number,
    cheque_mismo_banco?: number,
    cheque_otro_banco?: number,
    islr?: number,
    comision?: number,
    fecha_cheque_mismo_banco?: string,
    fecha_cheque_otro_banco?: string,
    conciliado?: boolean | number,
    fecha_conciliado?: string,
    islrnc?: number,
    riva?: number,
    estatus?: number,
    fecha_transaccion?: string,
    imagen?: string
}