export interface IMovimientosCaja {
    id?:string | number,
    caja_id?:string | number,
    fecha_at?:string,
    fecha_in?:string,
    hora_in?:string,
    tipo_pago_id?:string | number,
    tipo_movimiento_id?:string | number,
    banco_id?:string | number,
    referencia:string,
    debito:number,
    credito:number,
    credito_dolar:number,
    descripcion?:string,
    origen?:string,
    numero_origen:string,
    entidad_id?:string | number,
    islrnc?:number,
    riva?:number,
    fecha_transaccion?:string,
    imagen?:string
}