export interface ICliente {
    id?: string | number,
    nombre: string,
    nombre_comercial?: string,
    cedula: string,
    fecha_at: string,
    fecha_in: string,
    fecha_nac: string
    sexo: string,
    tipo_status_id: string | number,
    telefono1: string,
    telefono2: string,
    telefono3: string,
    direccion: string,
    direccion_fisica: string,
    horario: string,
    descuento: number,
    grupo_cliente_id: string | number,
    limite_credito: number,
    tarifa: string,
    contribuyente: string,
    cobrador_id: string | number,
    vendedor_id: string | number,
    zonas_id: string | number,
    correo_electronico: string,
    correo_electronico2: string,
    pag_web: string,
    dias_credito: number,
    creditos: number,
    contacto: string,
    telefono_contacto: string,
    observacion: string,
    estado_id: string | number,
    ciudad_id: string | number,
    empleado: number,
    usuario_id: string | number,
    imagen: string,
}