export interface ICompras{
    id?:                        string | number,
    numero_factura?:            string | number,
    adm_proveedor_id?:          number,
    adm_enc_orden_compra_id?:   number,
    adm_enc_recepcion_id?:      number,
    fecha_at?:                  string,
    numero_control?:            string,
    fecha_in?:                  string,
    subtotal?:                  string | number,
    subtotal_dolar?:            string | number,
    descuento?:                 string | number,
    descuento_dolar?:           string | number,
    descuento_global?:          string | number,
    descuento_global_dolar?:    string | number,
    iva?:                       string | number,
    retencion?:                 string | number,
    abono?:                     string | number,
    abono_dolar?:               string | number,
    status?:                    string | number,
    observacion?:               string,
    fecha_compra?:              string,
    riva?:                      string | number,
    procesado?:                 string | number,
    imagen?:                    string,
    detalles?:                  IDetCompras[],
}

export interface IDetCompras{
    id?:                string | number,
    adm_enc_compra_id?: string | number,
    adm_depositos_id?:  string | number,
    adm_conceptos_id?:  string | number,
    costo?:             string | number,
    descuento?:         string | number,
    cantidad?:          string | number,
    iva?:               string | number,
    serial_inicial?:    string,
    serial_final?:      string,
}