import { IGrupo } from "components/grupos/model";
import { ISubgrupo } from "components/subgrupos/model";

export interface IConcepto {
	id?: string | number | undefined;
	adm_empresa_id: string | number;
	codigo?: string | number;
	referencia?: string | number;
	nombre: string;
	descripcion?: string;
	talla?: string;
	color?: string;
	descuento?: number;
	serial_estatico?: number;
	serial_dinamico?: number;
	existencia_minima?: number;
	existencia_maxima?: number;
	tipos_conceptos_id: number | string;
	ubicacion_id?: number | string;
	costo?: number;
	ultimo_costo?: number;
	costo_mayor?: number;
	costo_promedio?: number;
	fecha_at: string;
	fecha_in?: string;
	fecha_uc?: string;
	grupos_id?: number | string;
	subgrupos_id?: number | string;
	presentacion?: number;
	unidades_id?: number | string;
	fecha_hora?: number;
	marcas_id?: number | string;
	estado?: boolean | number;
	pvp?: number;
	precio_a: number;
	precion_b?: number;
	precio_dolar: number;
	utilidad?: number;
	utiliad_a?: number;
	utilidad_b?: number;
	utilidad_c?: number;
	utilidad_dolar?: number;
	costo_dolar: number;
	precio_variante?: number;
	retiene?: boolean | number;
	farm_principio_activo_id?: number | string;
	imagen?: string;
	costo_adicional?: number;
	costo_adicional2?: number;
	cant_ensamblado?: number;
	licor?: boolean | number;
	porcentaje?: number;
	visible_pv?: boolean | number;
	visible_web?: boolean | number;
	rest_areas_id?: number | string;
	setcortesia?: boolean | number;
	exento?: boolean | number;
	merma?: boolean | number;
	exitencia_c?: number;
	obviar_ajuste?: boolean | number;
	iva?: boolean | number;
	presentaciones?: any[];
	existencias?: any[];
	grupo?: IGrupo;
	subgrupo?: ISubgrupo;
	isSold?: Boolean;
}

export interface IPresentaciones {}
