import {Application} from 'express';
import grupo from './components/grupos/route';
import subgrupos from './components/subgrupos/route';
import conceptos from './components/conceptos/route';
import marcas from './components/marcas/route';
import unidades from './components/unidades/route';
import depositos from './components/depositos/route';
import movDep from './components/movimiento_deposito/route';
import areasAtencion from './components/areas_atencion/route';
import banco from './components/banco/route';
import cambio from './components/cambio/route';
import cargos from './components/cargos/route';
import ciudad from './components/ciudad/route';
import clientes from './components/clientes/route';
import descargos from './components/descargos/route';
import empresa from './components/empresa/route';
import entidad from './components/entidad/route';

export const routes =  (app:Application) =>{
    app.use('/api/grupos',grupo);
    app.use('/api/subgrupos',subgrupos);
    app.use('/api/conceptos',conceptos);
    app.use('/api/marcas',marcas);
    app.use('/api/unidades',unidades);
    app.use('/api/depositos',depositos);
    app.use('/api/movimiento_deposito',movDep);
    app.use('/api/areas_atencion',areasAtencion);
    app.use('/api/banco',banco);
    app.use('/api/cambio',cambio);
    app.use('/api/cargos',cargos);
    app.use('/api/ciudad',ciudad);
    app.use('/api/clientes',clientes);
    app.use('/api/descargos',descargos);
    app.use('/api/empresa',empresa);
    app.use('/api/entidad',entidad);
};